# Copyright (c) 2026 ADBC Drivers Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

druid.service=druid/router
druid.plaintextPort=8888
druid.enablePlaintextPort=true
druid.tlsPort=9088
druid.enableTlsPort=true

druid.server.https.keyStorePath=/opt/druid/ci/certs/localhost.p12
druid.server.https.keyStoreType=PKCS12
druid.server.https.keyStorePassword=druid-dev
druid.server.https.keyManagerPassword=druid-dev
druid.server.https.certAlias=druid-dev

druid.router.http.numConnections=50
druid.router.http.readTimeout=PT5M
druid.router.http.numMaxThreads=100
druid.server.http.numThreads=100

druid.router.defaultBrokerServiceName=druid/broker
druid.router.coordinatorServiceName=druid/coordinator
druid.router.managementProxy.enabled=true
