[pytest]
junit_suite_name = validation
junit_duration_report = call
xfail_strict = true

markers =
    feature: test for a driver-specific feature

filterwarnings =
    error
    ignore:record_property is incompatible with junit_family:pytest.PytestWarning
